app/cart/forms.py
# from flask_wtf import FlaskForm
# from flask_wtf.recaptcha import validators
# from wtforms import IntegerField
# from wtforms.validators import DataRequired


# class CartForm(FlaskForm):
#     quantity = IntegerField('quantity', validators=[DataRequired()])

app/cart/routes.py
from flask import (
    Blueprint, 
    render_template, 
    redirect, 
    request, 
    session,
    flash,
)
from flask.helpers import url_for
from flask_login import login_required


from app.product.models import Product
from app.order.forms import OrderForm
from app.extensions import db

blueprint = Blueprint('carts', __name__)


def MagerDict(dict1, dict2):
    if isinstance(dict1, list) and isinstance(dict2, list):
        return dict1 + dict2
    elif isinstance(dict1, dict) and isinstance(dict2, dict):
        return dict(list(dict1.items()) + list(dict2.items()))
    return False


@blueprint.route('/add-cart', methods=['post'])
@login_required
def add_cart():
    try:
        product_id = request.form.get('product_id')
        quantity = request.form.get('quantity')
        product = Product.query.filter_by(id=product_id).first()
        if product_id and quantity and request.method == 'POST':
            dictItems = {
                product_id: {
                    'title': product.title,
                    'price': product.price,
                    'discount': product.discount,
                    'quantity': quantity
                    }
                }
            if 'Shoppingcart' in session:
                print(session['Shoppingcart'])
                if product_id in session['Shoppingcart']:
                    for key, item in session['Shoppingcart'].items():
                        if int(key) == int(product_id):
                            session.modified = True
                            item['quantity'] += 1
                else:
                    session['Shoppingcart'] = MagerDict(session['Shoppingcart'], dictItems)
                    return redirect(request.referrer)
            else:
                session['Shoppingcart'] = dictItems
                return redirect(request.referrer)
    except Exception as e:
        print(e)
    finally:
        return redirect(request.referrer)


@blueprint.route('/carts')
@login_required
def getCart():
    form = OrderForm()
    if 'Shoppingcart' not in session or len(session['Shoppingcart']) <= 0:
        return redirect(url_for('products.index'))
    total_price = 0
    grand_total = 0
    for key, product in session['Shoppingcart'].items():
        discount = (product['discount'] / 100) * float(product['price'])
        total_price += float(product['price']) * int(product['quantity'])
        total_price -= discount
        tax = ('%0.2f'% (0.6 * float(total_price)))
        grand_total = float('%0.2f'% (1.06 * total_price)) 
    return render_template('cart/detail.html', grand_total=grand_total, tax=tax, form=form)


@blueprint.post('/update-cart/<int:id>')
@login_required
def updateCart(id):
    if 'Shoppingcart' not in session and len(session['Shoppingcart']) <= 0:
        return redirect(url_for('products.index'))
    if request.method == 'POST':
        quantity = request.form.get('quantity')
        try:
            session.modified = True
            for key, item in session['Shoppingcart'].items():
                if int(key) == id:
                    item['quantity'] = quantity
                    flash('Item updated successfully', 'success')
                    return redirect(url_for('carts.getCart'))
        except Exception as e:
            return redirect(url_for('carts.getCart'))


@blueprint.route('/delete-cart/<int:id>')
@login_required
def deleteCart(id):
    if 'Shoppingcart' not in session and len(session['Shoppingcart']) <= 0:
        return redirect(url_for('products.index'))
    try:
        session.modified = True
        for key, item in session['Shoppingcart'].items():
            if int(key) == id:
                session['Shoppingcart'].pop(key, None)
                return redirect(url_for('carts.getCart'))
    except Exception as e:
            return redirect(url_for('carts.getCart'))


@blueprint.route('/clear-cart')
@login_required
def clearCart():
    try:
        session.pop('Shoppingcart')
        return redirect(url_for('products.index'))
    except Exception as e:
        return redirect(url_for('carts.getCart'))

app/order/routes.py
from flask import (
    Blueprint, 
    render_template, 
    flash, 
    redirect,
    url_for,
    request,
    session,
)
from flask_login import login_required, current_user
from decouple import config

from .forms import OrderForm
from .models import Order, OrderItem

from app.extensions import db
import stripe

blueprint = Blueprint('orders', __name__)

publishable_key = config('publishable_key')

stripe.api_key = config('stripe.api_key')

@blueprint.post('/payment')
@login_required
def payment():
    customer = stripe.Customer.create(
        email=request.form['stripeEmail'],
        source=request.form['stripeToken'],
    )

    charge = stripe.Charge.create(
        customer=customer.id,
        description='Myshop',
        amount=500,
        currency='usd',
    )
    orders = OrderItem.query.filter_by(user_id=current_user.id).order_by(
        OrderItem.id.desc()).first()
    return redirect(url_for('orders.thank'))


@blueprint.get('/payment-success')
def thank():
    return render_template('order/thank.html')


@blueprint.get('/order/<int:id>')
@login_required
def orderDetail(id):
    orders = OrderItem.query.filter_by(id=id).order_by(OrderItem.id.desc()).first()
    total_price = 0
    grand_price = 0
    for key, item in session['Shoppingcart'].items():
        discount = (item['discount'] / 100) * float(item['price'])
        total_price += float(item['price']) * int(item['quantity'])
        total_price -= discount
        tax = ('%0.2f'% (0.6 * float(total_price)))
        grand_total = ('%0.2f'% (1.06 * float(total_price)))
    return render_template('order/detail.html', orders=orders, grand_total=grand_total)


@blueprint.post('/order')
@login_required
def createOrder():
    if request.method == 'POST':
        form = OrderForm()
        if form.validate_on_submit():
            order = Order(
                user_id=current_user.id,
                name=form.name.data,
                country=form.country.data,
                city=form.city.data,
                address=form.address.data,
                contact=form.contact.data,
                zip_code=form.zip_code.data
            )
            db.session.add(order)
            db.session.commit()
        for key, item in session['Shoppingcart'].items():
            orderItem = OrderItem(
                order_id=order.id,
                user_id=current_user.id, 
                product_id=key, 
                quantity=item['quantity']
            )
            db.session.add(orderItem)
            db.session.commit()
            flash('Order created successfully', 'success')
        return redirect(url_for('orders.orderDetail', id=order.id))

app/templates/cart/detail.html
{% extends 'base.html' %}

{% block title %} Carts {% endblock %}


{% block content %}
    <table class="table">
        <thead>
            <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Discount</th>
            <th scope="col">TotalPrice</th>
            <th scope="col">Update</th>
            <th scope="col">Remove</th>
            </tr>
        </thead>
        <tbody>
            {% for key, product in session['Shoppingcart'].items() %}
            {% set discount = '%0.2f'|format(( product.discount / 100 ) * product.price|float) %}
            <tr>
                <th scope="row">{{ loop.index }}</th>
                <td>{{ product.title }}</td>
            <form method='post' action='{{ url_for('carts.updateCart', id=key) }}'>
                <td>{{ product.price }}</td>
                <td><input name='quantity' type='number' value='{{ product.quantity }}'
                min='1' max='{{ product.stock }}'></td>
                <td>{{ product.discount }}% is {{ discount }}</td>
                {% set TotalPrice = product.quantity|int * product.price|float %}
                <td>{{ '%0.2f'|format((TotalPrice|float) - discount|float) }}</td>
                <td><button type='submit' class='btn btn-outline-info btn-sm'>Update</button></td>
            </form>
                <td><a href='{{ url_for('carts.deleteCart', id=key) }}' class='btn btn-outline-warning btn-sm'>Remove</a></td>
            </tr>
            {% endfor %}

            <tr>
                <td></td>
                <td colspan='3'><h5>Tax: ${{ tax }}</h5></td>
                <td colspan='3'><h5>GrandTotal: ${{ grand_total }}</h5></td>
                <td><a href='{{ url_for('carts.clearCart') }}' class='btn btn-outline-danger btn-sm'>Clear</a></td>
            </tr>
        </tbody>
    </table>

     <form method='post' action='{{ url_for('orders.createOrder') }}' novalidate>
        {{ form.csrf_token }}
        {{ form.name.label(class='form-control-label') }} {{ form.name(class='form-control') }}
        {% if form.name.errors %}
            {% for error in form.name.errors %}
                <p class='alert alert-danger'>{{ error }}</p>
            {% endfor %}
        {% endif %}
        {{ form.country.label(class='form-control-label') }} {{ form.country(class='form-control') }}
        {% if form.country.errors %}
            {% for error in form.country.errors %}
                <p class='alert alert-danger'>{{ error }}</p>
            {% endfor %}
        {% endif %}
        {{ form.city.label(class='form-control-label') }} {{ form.city(class='form-control') }}
        {% if form.city.errors %}
            {% for error in form.city.errors %}
                <p class='alert alert-danger'>{{ error }}</p>
            {% endfor %}
        {% endif %}
        {{ form.address.label(class='form-control-label') }} {{ form.address(class='form-control') }}
        {% if form.address.errors %}
            {% for error in form.address.errors %}
                <p class='alert alert-danger'>{{ error }}</p>
            {% endfor %}
        {% endif %}
        {{ form.contact.label(class='form-control-label') }} {{ form.contact(class='form-control') }}
        {% if form.contact.errors %}
            {% for error in form.contact.errors %}
                <p class='alert alert-danger'>{{ error }}</p>
            {% endfor %}
        {% endif %}
        {{ form.zip_code.label(class='form-control-label') }} {{ form.zip_code(class='form-control') }}
        {% if form.zip_code.errors %}
            {% for error in form.zip_code.errors %}
                <p class='alert alert-danger'>{{ error }}</p>
            {% endfor %}
        {% endif %}

        <button type='submit' class='btn btn-outline-primary'>Confirm</button>
    </form> 
{% endblock %}