app/product/models.py
from app.extensions import db, admin
from app.database import BaseModel

from flask_admin.contrib.sqla import ModelView


class Product(BaseModel):
    __searchable__ = ['title', 'description']

    title = db.Column(db.String(50), unique=True, nullable=False)
    description = db.Column(db.String(300))
    price = db.Column(db.Integer, nullable=False)
    stock = db.Column(db.Integer)
    discount = db.Column(db.Integer, nullable=True)
    available = db.Column(db.Boolean, default=True)
    image = db.Column(db.LargeBinary, nullable=True)

    category_id = db.Column(db.Integer, db.ForeignKey('category.id'), nullable=False)
    category = db.relationship('Category', backref='categories', lazy=True)

    def __repr__(self):
        return f'{self.__class__.__name__} ({self.id}-{self.title})'


class Category(BaseModel):
    title = db.Column(db.String(50), unique=True, nullable=False)

    def __repr__(self):
        return f'{self.__class__.__name__} ({self.id}-{self.title})'


admin.add_view(ModelView(Product, db.session, url='admin-product'))
admin.add_view(ModelView(Category, db.session))

app/product/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import (
    FileField, 
    FileRequired,
    FileAllowed,
)
from wtforms import (
    StringField, 
    BooleanField, 
    TextAreaField,
    IntegerField,
)
from wtforms.validators import DataRequired, ValidationError

from .models import Category, Product


class AddProduct(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    description = TextAreaField('Description')
    price = IntegerField('Price', validators=[DataRequired()])
    stock = IntegerField('Stock', validators=[DataRequired()])
    discount = IntegerField('Discount', default=0)
    available = BooleanField('Available')
    image = FileField('Image')

    def validate_title(self, title):
        product = Product.query.filter_by(title=title.data).first()
        if product:
            raise ValidationError(f'Product with this title already exists.')


class AddCategory(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])

    def validate_title(self, title):
        cat = Category.query.filter_by(title=title.data).first()
        if cat:
            raise ValidationError(f'Category with this title already exists.')

app/cart/routes.py
from flask import (
    Blueprint, 
    render_template, 
    redirect, 
    request, 
    session,
    flash,
)
from flask.helpers import url_for
from flask_login import login_required


from app.product.models import Product
from app.order.forms import OrderForm
from app.extensions import db

blueprint = Blueprint('carts', __name__)


def MagerDict(dict1, dict2):
    if isinstance(dict1, list) and isinstance(dict2, list):
        return dict1 + dict2
    elif isinstance(dict1, dict) and isinstance(dict2, dict):
        return dict(list(dict1.items()) + list(dict2.items()))
    return False


@blueprint.route('/add-cart', methods=['post'])
@login_required
def add_cart():
    try:
        product_id = request.form.get('product_id')
        quantity = request.form.get('quantity')
        product = Product.query.filter_by(id=product_id).first()
        if product_id and quantity and request.method == 'POST':
            dictItems = {
                product_id: {
                    'title': product.title,
                    'price': product.price,
                    'discount': product.discount,
                    'quantity': quantity
                    }
                }
            if 'Shoppingcart' in session:
                print(session['Shoppingcart'])
                if product_id in session['Shoppingcart']:
                    for key, item in session['Shoppingcart'].items():
                        if int(key) == int(product_id):
                            session.modified = True
                            item['quantity'] += 1
                else:
                    session['Shoppingcart'] = MagerDict(session['Shoppingcart'], dictItems)
                    return redirect(request.referrer)
            else:
                session['Shoppingcart'] = dictItems
                return redirect(request.referrer)
    except Exception as e:
        print(e)
    finally:
        return redirect(request.referrer)


@blueprint.route('/carts')
@login_required
def getCart():
    form = OrderForm()
    if 'Shoppingcart' not in session or len(session['Shoppingcart']) <= 0:
        return redirect(url_for('products.index'))
    total_price = 0
    grand_total = 0
    for key, product in session['Shoppingcart'].items():
        discount = (product['discount'] / 100) * float(product['price'])
        total_price += float(product['price']) * int(product['quantity'])
        total_price -= discount
        tax = ('%0.2f'% (0.6 * float(total_price)))
        grand_total = float('%0.2f'% (1.06 * total_price)) 
    return render_template('cart/detail.html', grand_total=grand_total, tax=tax, form=form)


@blueprint.post('/update-cart/<int:id>')
@login_required
def updateCart(id):
    if 'Shoppingcart' not in session and len(session['Shoppingcart']) <= 0:
        return redirect(url_for('products.index'))
    if request.method == 'POST':
        quantity = request.form.get('quantity')
        try:
            session.modified = True
            for key, item in session['Shoppingcart'].items():
                if int(key) == id:
                    item['quantity'] = quantity
                    flash('Item updated successfully', 'success')
                    return redirect(url_for('carts.getCart'))
        except Exception as e:
            return redirect(url_for('carts.getCart'))


@blueprint.route('/delete-cart/<int:id>')
@login_required
def deleteCart(id):
    if 'Shoppingcart' not in session and len(session['Shoppingcart']) <= 0:
        return redirect(url_for('products.index'))
    try:
        session.modified = True
        for key, item in session['Shoppingcart'].items():
            if int(key) == id:
                session['Shoppingcart'].pop(key, None)
                return redirect(url_for('carts.getCart'))
    except Exception as e:
            return redirect(url_for('carts.getCart'))


@blueprint.route('/clear-cart')
@login_required
def clearCart():
    try:
        session.pop('Shoppingcart')
        return redirect(url_for('products.index'))
    except Exception as e:
        return redirect(url_for('carts.getCart'))

app/product/routes.py
from flask import (
    Blueprint, 
    render_template,
    request,
    flash,
    url_for,
    redirect,
)
from flask_paginate import get_page_parameter

from .models import Product, Category
from .forms import AddProduct

from app.extensions import db, search

blueprint = Blueprint('products', __name__)


@blueprint.get('/')
def index():
    page = request.args.get(get_page_parameter(), type=int, default=1)
    get_products = Product.query.filter_by(available=True).paginate(page=page, per_page=3)
    return render_template('product/index.html', get_products=get_products)


@blueprint.get('/result')
def result():
    searchWord = request.args.get('q')
    products = Product.query.msearch(searchWord, fields=['title', 'description'], limit=3)
    return render_template('product/result.html', products=products)


@blueprint.route('/<product_id>', methods=['get', 'post'])
def product_detail(product_id):
    product = Product.query.get_or_404(product_id)
    return render_template('product/detail.html', product=product)


@blueprint.route('/add-product', methods=['get', 'post'])
def add_product():
    categories = Category.query.all()
    form = AddProduct()
    if form.validate_on_submit():
        product = Product(
            title=form.title.data,
            description=form.description.data,
            price=form.price.data,
            stock=form.stock.data,
            discount=form.discount.data,
            available=form.available.data,
            category_id=request.form.get('category'),
        )
        db.session.add(product)
        db.session.commit()
        flash(f'Product added successfully', 'success')
        return redirect(url_for('products.add_product'))
    return render_template('product/add.html', form=form, categories=categories)


# @blueprint.route('/add-cat', methods=['get', 'post'])
# def add_cat():
#     form = AddCategory()
#     if form.validate_on_submit():
#         cat = Category(
#             title=form.title.data
#         )
#         db.session.add(cat)
#         db.session.commit()
#         flash(f'Category added successfully', 'success')
#         return redirect(url_for('products.add_cat'))
#     return render_template('product/add_cat.html', form=form)

app/templates/product/add.html
{% extends 'base.html' %}

{% block title %} Add Product {% endblock %}


{% block content %}
    <form method='post' enctype='multipart/form-data' novalidate>
        {{ form.csrf_token }}
        {{ form.title.label(class='form-control-label') }} {{ form.title(class='form-control') }}
        {% if form.title.errors %}
            {% for error in form.title.errors %}
                <p class='alert alert-danger'>{{ error }}</p>
            {% endfor %}
        {% endif %}
        {{ form.description.label(class='form-control-label') }} {{ form.description(class='form-control') }}
        {% if form.description.errors %}
            {% for error in form.description.errors %}
                <p class='alert alert-danger'>{{ error }}</p>
            {% endfor %}
        {% endif %}
        {{ form.price.label(class='form-control-label') }} {{ form.price(class='form-control') }}
        {% if form.price.errors %}
            {% for error in form.price.errors %}
                <p class='alert alert-danger'>{{ error }}</p>
            {% endfor %}
        {% endif %}
        {{ form.stock.label(class='form-control-label') }} {{ form.stock(class='form-control') }}
        {% if form.stock.errors %}
            {% for error in form.stock.errors %}
                <p class='alert alert-danger'>{{ error }}</p>
            {% endfor %}
        {% endif %}
        {{ form.discount.label(class='form-control-label') }} {{ form.discount(class='form-control') }}
        {% if form.discount.errors %}
            {% for error in form.discount.errors %}
                <p class='alert alert-danger'>{{ error }}</p>
            {% endfor %}
        {% endif %}
        {{ form.available.label }} {{ form.available }}

        <select name='category' id='category' class='form-control' required>
            <option value=''>Select a category</option>
            {% for category in categories %}
                <option value='category.id'>{{ category.title }}</option>
            {% endfor %}
        </select>



        <input type='file' name='file'><br><br>

        <button type='submit' class='btn btn-outline-primary'>confirm</button>
    </form>
{% endblock %}

app/templates/product/add_cat.html
{% extends 'base.html' %}

{% block title %} Add Category {% endblock %}


{% block content %}
    <form method='post'>
        {{ form.csrf_token }}
        {{ form.title.label(class='form-control-label') }} {{ form.title(class='form-control') }}
        {% if form.title.errors %}
            {% for error in form.title.errors %}
                <p class='alert alert-danger'>{{ error }}</p>
            {% endfor %}
        {% endif %}<hr>
        <button type='submit' class='btn btn-outline-primary'>confirm</button>
    </form>
{% endblock %}

app/templates/product/detail.html
{% extends 'base.html' %}

{% block title %} {{ product.title }} {% endblock %}


{% block content %}
    <p>{{ product.title }}</p>
    <small>{{ product.price }}</small>

    <form method='post' action='{{ url_for('carts.add_cart') }}'>
        {{ csrf_token }}
        <input type='hidden' name='product_id' value='{{ product.id }}'>
        <button type='submit' class='btn btn-outline-primary'>Add to cart</button>
        <label>Quantity:</label>
        <input type='number' name='quantity' id='' value='1' min='1' max='{{ product.stock }}'>     
    </form>
{% endblock %}

app/templates/product/index.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}


{% block content %}
    <div class='card'>
        {% for product in get_products.items %}
            <a href='{{ url_for('products.product_detail', product_id=product.id) }}' class='card-body'>{{ product.title }}</a>

            {% if product.discount > 0 %}
                <p>Discount {{ product.discount }}%</p>
            {% endif %}
            <small>${{ product.price }}</small><hr>

        {% endfor %}
    </div>


    {% if get_products.has_prev %}
        <a href='{{ url_for('products.index', page=get_products.prev_num) }}' class='btn btn-outline-info btn-sm'>previous</a>
    {% endif %}
    {% for page_num in get_products.iter_pages(left_edge=1, right_edge=2, left_current=1, right_current=2) %}
    {% if page_num %}
    {% if get_products.page == page_num %}
        <a href='{{ url_for('products.index', page=page_num) }}' class='btn btn-info btn-sm'>{{ page_num }}</a>
    {% else %}
        <a href='{{ url_for('products.index', page=page_num) }}' class='btn btn-outline-info btn-sm'>{{ page_num }}</a>
    {% endif %}
    {% else %}
        ...
    {% endif %}
    {% endfor %}

    {% if get_products.has_next %}
        <a href='{{ url_for('products.index', page=get_products.next_num) }}' class='btn btn-outline-info btn-sm'>next</a>
    {% endif %}
{% endblock %}

app/templates/product/result.html
{% extends 'base.html' %}

{% block title %} Home {% endblock %}


{% block content %}
    <div class='card'>
        {% for product in products %}
            <a href='{{ url_for('products.product_detail', product_id=product.id) }}' class='card-body'>{{ product.title }}</a>

            {% if product.discount > 0 %}
                <p>Discount {{ product.discount }}%</p>
            {% endif %}
            <small>${{ product.price }}</small><hr>

        {% endfor %}
    </div>
{% endblock %}