app/product/routes.py
from flask import (
    Blueprint, 
    render_template,
    request,
    flash,
    url_for,
    redirect,
)
from flask_paginate import get_page_parameter

from .models import Product, Category
from .forms import AddProduct

from app.extensions import db, search

blueprint = Blueprint('products', __name__)


@blueprint.get('/')
def index():
    page = request.args.get(get_page_parameter(), type=int, default=1)
    get_products = Product.query.filter_by(available=True).paginate(page=page, per_page=3)
    return render_template('product/index.html', get_products=get_products)


@blueprint.get('/result')
def result():
    searchWord = request.args.get('q')
    products = Product.query.msearch(searchWord, fields=['title', 'description'], limit=3)
    return render_template('product/result.html', products=products)


@blueprint.route('/<product_id>', methods=['get', 'post'])
def product_detail(product_id):
    product = Product.query.get_or_404(product_id)
    return render_template('product/detail.html', product=product)


@blueprint.route('/add-product', methods=['get', 'post'])
def add_product():
    categories = Category.query.all()
    form = AddProduct()
    if form.validate_on_submit():
        product = Product(
            title=form.title.data,
            description=form.description.data,
            price=form.price.data,
            stock=form.stock.data,
            discount=form.discount.data,
            available=form.available.data,
            category_id=request.form.get('category'),
        )
        db.session.add(product)
        db.session.commit()
        flash(f'Product added successfully', 'success')
        return redirect(url_for('products.add_product'))
    return render_template('product/add.html', form=form, categories=categories)


# @blueprint.route('/add-cat', methods=['get', 'post'])
# def add_cat():
#     form = AddCategory()
#     if form.validate_on_submit():
#         cat = Category(
#             title=form.title.data
#         )
#         db.session.add(cat)
#         db.session.commit()
#         flash(f'Category added successfully', 'success')
#         return redirect(url_for('products.add_cat'))
#     return render_template('product/add_cat.html', form=form)

app/user/routes.py
from flask import (
    Blueprint, 
    render_template, 
    url_for, 
    redirect,
    flash,
    request,
)
from flask_login import (
    login_user, 
    logout_user, 
    current_user,
    login_required,
)

from .models import User
from .forms import UserSignUpForm, UserSignInForm
from app.extensions import db, bcrypt

blueprint = Blueprint('users', __name__)


@blueprint.route('/sign-up', methods=['post', 'get'])
def sign_up():
    if current_user.is_authenticated:
        flash('You are sign-up already', 'warning')
        return redirect(url_for('products.index'))
    form = UserSignUpForm()
    if form.validate_on_submit():
        password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(
            username=form.username.data,
            email=form.email.data,
            password=password
        )
        db.session.add(user)
        db.session.commit()
        flash('Signed-Up successfully', 'info')
        return redirect(url_for('products.index'))
    return render_template('user/sign_up.html', form=form)


@blueprint.route('/sign-in', methods=['post', 'get'])
def sign_in():
    if current_user.is_authenticated:
        flash('You are sign-in already', 'warning')
        return redirect(url_for('products.index'))
    form = UserSignInForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next', None)
            flash('Sign-In successfully', 'info')
            return redirect(next_page if next_page else url_for('products.index'))
        else:
            flash('Email or Password is incorrect', 'danger')
    return render_template('user/sign_in.html', form=form)


@blueprint.route('/sign-out')
@login_required
def sign_out():
    logout_user()
    flash('Sign-Out successfully', 'info')
    return redirect(url_for('products.index'))

app/templates/includes/messages.html
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    <ul class=flashes>
    {% for category, message in messages %}
      <li class="alert alert-{{ category }}">{{ message }}</li>
    {% endfor %}
    </ul>
  {% endif %}
{% endwith %}

app/templates/includes/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Home</a>
  {% if not current_user.is_authenticated %}
    <a class="navbar-brand" href="{{ url_for('users.sign_up') }}">sign-up</a>
    <a class="navbar-brand" href="{{ url_for('users.sign_in') }}">sign-in</a>
  {% else %}
    <a class="navbar-brand" href="{{ url_for('carts.getCart') }}">Cart ({{ session['Shoppingcart']|length }})</a>
    <a class="navbar-brand" href="{{ url_for('users.sign_out') }}">sign-out</a>
  {% endif %}

  <form class="d-flex" action='{{ url_for('products.result') }}'>
      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name='q'>
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
</nav>